### ISSUE TITLE
Custom API Key Not Working

### ISSUE THREAD

**Issue by godofpainTR** [RuurdBijlsma/locationestimatr2#2]
I got myself a custom API key and pasted it in the relevant input in the settings, then applied it. But I still get the watermark and negative colors.

**Comment by RuurdBijlsma** [comment]
do you have billing enabled for the api key? that's required

**Comment by godofpainTR** [comment]
Ooh, that's what I was missing. Then it seems like we're both stuck because I don't have a credit card either. Wish we could use money from youtube or opinion rewards for this.
