### ISSUE TITLE
game loading indefinetly 

### ISSUE THREAD

**Issue by craftycram** [RuurdBijlsma/locationestimatr2#20]
Hey, I've been trying to setup my own hosted version of locationsestimatr.
I got everything setup, but once i try to play a map it just loads forever, as you can see in the screenshot.

![grafik](https://user-images.githubusercontent.com/32396733/120119339-89241d80-c197-11eb-8df3-f9be7be5774a.png)

There aren't any error messages in the browser console.
Do you have any idea what could cause that problem?

**Comment by craftycram** [comment]
Also just another thing. Not sure if they correspond with each other, but on the start screen there's also an indefinitely "Loading Maps" and on the explore page it doesn't show any maps, although I created one.

![grafik](https://user-images.githubusercontent.com/32396733/120119790-fb95fd00-c199-11eb-9dab-7ad55513b1e7.png)
![grafik](https://user-images.githubusercontent.com/32396733/120119794-03ee3800-c19a-11eb-93cf-15ce1fb18361.png)

**Comment by RuurdBijlsma** [comment]
Have you set up the firebase database? does it connect to that? Locationestimatr2 is pretty complex to set up, it might be easier to host the first version https://github.com/locationestimatr/locationestimatr.github.io

It's been a long time since I've worked on this so I probably wont be able to figure out what's going wrong here without being able to reproduce it easily myself

**Comment by craftycram** [comment]
Hey, thanks for the quick reply yes everything is setup. I also see the users and maps in the database.
I already have the first version running, but I always used the second version on locationestimatr.web.app and would prefer using that again. Since the mentioned version isn't online anymore I wanted to deploy my own one ^^

I can also see the map on my profile. But clicking play loads forever
![grafik](https://user-images.githubusercontent.com/32396733/120120287-87a92400-c19c-11eb-8a8a-803e6d2c7929.png)

**Comment by craftycram** [comment]
I followed all the steps mentioned here to deploy it: https://github.com/RuurdBijlsma/locationestimatr2/blob/master/selfhost.md

**Comment by RuurdBijlsma** [comment]
If literally nothing is being logged to the console then maybe https://github.com/RuurdBijlsma/locationestimatr2/blob/master/src/main.js#L6 is preventing the logs. Without an error I have no idea what it could be

Remove lines 5 and 6 there and see if it logs stuff

**Comment by craftycram** [comment]
I wasn't testing it in production, but tested it anyways. Sadly didn't work.
There is some logging, but no errors as you can see below.

```
Using cached shallowMap:FXNH2u7ijalDyhdgTcPJ index.js:58
Not using cached user:sbHECYPi8OdZShEArH8MfkMH8T72 index.js:51
Object { likes: Getter & Setter, maps: Getter & Setter, date: Getter & Setter, name: Getter & Setter, … }
Profile.vue:69
Using cached map:FXNH2u7ijalDyhdgTcPJ index.js:58
Using cached storage:image:/images/user/FXNH2u7ijalDyhdgTcPJ index.js:58
?MAP ID 
Object { name: "internationalgang", image: "/images/user/FXNH2u7ijalDyhdgTcPJ", settings: {…}, realUser: true, kml: "<MultiGeometry>\n<Polygon><outerBoundaryIs><LinearRing><coordinates>\n-84.82000231861136,45.66653873007621,0 -86.62176013111136,43.85698993937649,0 -86.79754138111136,42.186486119671166,0 -87.89617419361136,41.53189743482081,0 -85.96258044361136,41.827291507236126,0 -83.67742419361136,41.4331315315343,0 -81.43621325611136,41.630512772994855,0 -78.88738513111136,42.83436646356131,0 -78.97527575611136,43.57111865859886,0 -76.60222888111136,43.730104396294834,0 -76.07488513111136,44.83121469324283,0 -80.90886950611136,45.850498121335605,0 \n</coordinates></LinearRing></outerBoundaryIs></Polygon>\n<Polygon><outerBoundaryIs><LinearRing><coordinates>\n7.631194688202871,53.44874738891203,0 7.367522813202871,52.41576172990626,0 6.884124375702871,51.44025053678623,0 6.620452500702871,50.83363462771126,0 6.928069688202871,50.275234816911315,0 7.323577500702871,49.68178231312819,0 8.290374375702871,49.052204837363625,0 8.378265000702871,48.67638779600575,0 8.026702500702871,47.97514729912979,0 9.213225938202871,48.063329827679155,0 10.575530625702871,47.91627513971872,0 12.201507188202871,48.063329827679155,0 12.421233750702871,48.32697276293185,0 12.816741563202871,48.85019251565276,0 12.465179063202871,49.368001332710136,0 11.981780625702871,50.16276038871656,0 12.157561875702871,50.944521541577494,0 13.344085313202871,51.0275135567725,0 14.047210313202871,51.60430965019683,0 13.959319688202871,52.49609875959766,0 13.783538438202871,53.29142939883751,0 13.959319688202871,53.78761287312473,0 12.728850938202871,54.32927984104166,0 11.190765000702871,53.994795286011694,0 8.554046250702871,54.58473889859926,0 \n</coordinates></LinearRing></outerBoundaryIs></Polygon>\n</MultiGeometry>\n", date: {…}, user: "sbHECYPi8OdZShEArH8MfkMH8T72", type: "kml", id: "FXNH2u7ijalDyhdgTcPJ" }
MapManager.js:31
Object { __gjsload__: (), geometry: {…}, Animation: {…}, BicyclingLayer: zh(), Circle: tj(a), ControlPosition: {…}, Data: Ig(a), DirectionsRenderer: Ng(a), DirectionsService: Kg()
, DirectionsStatus: {…}, … }
Google.js:15
Object { area: 566186308369.0447 }
MapManager.js:76
MULTIPLIER 1 GeoMap.js:14
Map: 
Object { type: Getter & Setter, name: Getter & Setter, settings: Getter & Setter, id: Getter & Setter, maxScore: Getter & Setter, minimumDistanceForPoints: Getter & Setter, polygon: Getter & Setter, … }
PlayMap.vue:122
Starting game 
Object { type: Getter & Setter, name: Getter & Setter, settings: Getter & Setter, id: Getter & Setter, maxScore: Getter & Setter, minimumDistanceForPoints: Getter & Setter, polygon: Getter & Setter, … }
 
Object { zoomAllowed: Getter & Setter, panAllowed: Getter & Setter, unlimitedTime: Getter & Setter, unlimitedMoves: Getter & Setter, moveLimit: Getter & Setter, timeLimit: Getter & Setter, roundCount: Getter & Setter, objective: Getter & Setter, svType: Getter & Setter, distribution: Getter & Setter, … }
 null Game.vue:197
Using zoom level: 14 1504907.0514407787 Game.vue:214
googleMap 
Object { gm_bindings_: Getter & Setter, __gm: Getter & Setter, gm_accessors_: Getter & Setter, zoom: Getter & Setter, center: Getter & Setter, disableDefaultUI: Getter & Setter, clickableIcons: Getter & Setter, backgroundColor: Getter & Setter, fullscreenControl: Getter & Setter, mapTypeId: Getter & Setter, … }
Game.vue:253
Attach map to 
<div class="small-map" data-v-6ca3af22="">
Game.vue:526
AttachMap was 
<div class="map-element" data-v-6ca3af22="">
Game.vue:529
loadNextLocation, round: 1 Game.vue:499
Waiting for event: roundLocation:1
```

if you need the content of any of those objects just let me know

**Comment by RuurdBijlsma** [comment]
I think it's a problem with the random-streetview package I made. If you look at the network tab you may see it making a whole lot of requests. Can't fix that right now, not sure why it's broken, seeing as this link still works https://maps.googleapis.com/maps/vt?pb=!1m5!1m4!1i2!2i2!3i2!4i256!2m8!1e2!2ssvv!4m2!1scb_client!2sapiv3!4m2!1scc!2s*211m3*211e3*212b1*213e2*211m3*211e2*212b1*213e2!3m3!3sUS!12m1!1e68!4e0

**Comment by craftycram** [comment]
Yes I see a lot of requests (~3500 after 8 minutes). 

![grafik](https://user-images.githubusercontent.com/32396733/120155409-15aefa00-c1f1-11eb-93d6-f666ce0b04ae.png)

Also should the link you provided look like this?:
![grafik](https://user-images.githubusercontent.com/32396733/120155462-252e4300-c1f1-11eb-9471-3daefa666266.png)

**Comment by craftycram** [comment]
Just to make sure I got the deploy instructions right, the googleMapsKey and the streetViewKey in the credentials are the same and I only need to enable the Maps JavaScript API, not a separate StreetView API as well right?

**Comment by RuurdBijlsma** [comment]
Yea it's supposed to look like that, and the sv and maps key are the same I think yes (the sv key is just for the map editor to get static images from a point). However it looks like it's an issue with random-streetview then, I don't have time right now to fix that. You can look at it (github.com/ruurdbijlsma/random-streetview) to try to fix it yourself if you want

**Comment by craftycram** [comment]
Alright imma see what I can do about it. Appreciate the help and awesome project btw. I really enjoy playing it. Have been playing it the past few months for over 20 hours with some friends from CA and the US with custom maps to explore each others countries and hometowns.

**Comment by craftycram** [comment]
Gonna push updates in here if I find something that I can fix ^^

**Comment by RuurdBijlsma** [comment]
I fixed the random-streetview package @craftycram

**Comment by craftycram** [comment]
Oh epic. Thanks a lot!
Just out of interest, what was the issue?

**Comment by RuurdBijlsma** [comment]
Google changed the color of their street view road color at a certain zoom level https://i.imgur.com/N0T98x3.png 

This package uses images like that one to determine if there is streetview coverage and gets the type of coverage by comparing the colors. 

So the issue was that it never found streetview coverage anywhere and kept searching infinitely

**Comment by craftycram** [comment]
Oh I see. That sounds like a pain to debug ^^
