### ISSUE TITLE
Maximum amount of points for custom maps

### ISSUE THREAD

**Issue by Koenvh1** [RuurdBijlsma/locationestimatr2#3]
First of all: Thank you for creating this!

I was looking into the maximum amount of points for a polygon. I uploaded a KML of [Stockholm](https://locationestimatr.web.app/play?map=NzLANOvzdCHyiiX1CLJn) with 661 points, and I noticed that the website was slowing down a bit already. I had some ideas for more complex shapes (e.g. all motorways in the Netherlands), but I was wondering whether the website could handle that, and more importantly, whether that would break things for others as well (as I do not want that to happen).

**Comment by RuurdBijlsma** [comment]
The laggyness is only really a problem when in the map maker, when playing a map with a huge amount of points it doesn't affect it much. The map for Russia for example has 2100 points and works fine when playing (not when it's in the map maker though). Looking for a location in a map with many points is slower than on a map with a small amount of points, but a map with a massive amount of points won't break anything besides the map itself.

On a side note, the location finding algorithm isn't super accurate about staying within the polygon, so there's no point in making very detailed maps in the map editor.
