### ISSUE TITLE
Again API

### ISSUE THREAD

**Issue by katashibeats** [RuurdBijlsma/locationestimatr2#7]
I love your game but I ran into it today. Is it API related? Sry for my English. I`m from Russia
![Снимок](https://user-images.githubusercontent.com/68787297/88462823-96adae80-cec7-11ea-96f2-ab3e8ecb2b6d.JPG)

**Comment by Injazz** [comment]
yeah, probably month quota reached

**Comment by RuurdBijlsma** [comment]
Yup, I hope it works again at the start of the month
